export const PERMISSIONS = {
  AI: {
    AUTORESOLUTION_MANAGE: 'ai:autoresolution_manage',
    CONFIGURE: 'ai:configure',
    FEEDBACK: 'ai:feedback',
    READ: 'ai:read',
  },
  AUDIT: {
    EXPORT: 'audit:export',
    READ: 'audit:read',
    READ_ALL: 'audit:read_all',
  },
  COMPANY: {
    CREATE: 'company:create',
    DELETE: 'company:delete',
    MANAGE_CONTACTS: 'company:manage_contacts',
    MANAGE_DOMAINS: 'company:manage_domains',
    MANAGE_LIMITS: 'company:manage_limits',
    MANAGE_SLA: 'company:manage_sla',
    READ: 'company:read',
    READ_ALL: 'company:read_all',
    UPDATE: 'company:update',
    VIEW_HEALTH: 'company:view_health',
  },
  CONFIG: {
    MANAGE: 'config:manage',
  },
  CONTACT: {
    CREATE: 'contact:create',
    READ: 'contact:read',
    UPDATE: 'contact:update',
  },
  DASHBOARD: {
    ADMIN: 'dashboard:admin',
    READ: 'dashboard:read',
    WRITE: 'dashboard:write',
    CUSTOMER: 'dashboard:company',
    TEAMLEAD: 'dashboard:teamlead',
    MANAGER: 'dashboard:manager',
  },
  GAMIFICATION: {
    MANAGE: 'gamif:manage',
  },
  GROUP: {
    CREATE: 'group:create',
    DELETE: 'group:delete',
    MANAGE_LEADS: 'group:manage_leads',
    MANAGE_MEMBERS: 'group:manage_members',
    READ: 'group:read',
    READ_ALL: 'group:read_all',
    UPDATE: 'group:update',
  },
  KB: {
    CREATE: 'kb:create',
    PUBLISH: 'kb:publish',
    READ: 'kb:read',
    UPDATE: 'kb:update',
  },
  NOTIFICATION: {
    DELIVERY_LOGS: 'notification:delivery_logs',
    READ: 'notification:read',
    READ_ALL: 'notification:read_all',
    RESEND: 'notification:resend',
    TEMPLATE_MANAGE: 'notification:template_manage',
    WRITE: 'notification:write',
  },
  PERMISSION: {
    READ: 'permission:read',
    WRITE: 'permission:write',
  },
  REPORT: {
    EXPORT: 'report:export',
    READ: 'report:read',
    READ_ALL: 'report:read_all',
  },
  ROLE: {
    READ: 'role:read',
    WRITE: 'role:write',
  },
  SECURITY: {
    READ: 'security:read',
    READ_ALL: 'security:read_all',
  },
  SESSIONS: {
    MANAGE: 'sessions:manage',
  },
  SLA: {
    MANAGE: 'sla:manage',
  },
  TICKET: {
    ASSIGN: 'ticket:assign',
    ATTACHMENT_UPLOAD: 'ticket:attachment_upload',
    AUDIT: 'ticket:audit',
    BULK_ASSIGN: 'ticket:bulk_assign',
    BULK_UPDATE: 'ticket:bulk_update',
    CHANGE_GROUP: 'ticket:change_group',
    CHANGE_PRIORITY: 'ticket:change_priority',
    CLOSE: 'ticket:close',
    COMMENT: 'ticket:comment',
    CREATE: 'ticket:create',
    DELETE: 'ticket:delete',
    EXPORT: 'ticket:export',
    FORCE_CLOSE: 'ticket:force_close',
    MANAGE: 'ticket:manage',
    MERGE: 'ticket:merge',
    QUEUE_MANAGE: 'ticket:queue_manage',
    READ: 'ticket:read',
    READ_ALL: 'ticket:read_all',
    READ_ASSIGNED: 'ticket:read_assigned',
    READ_COMPANY: 'ticket:read_company',
    READ_OWN: 'ticket:read_own',
    READ_QUEUE: 'ticket:read_queue',
    READ_TEAM: 'ticket:read_team',
    REASSIGN: 'ticket:reassign',
    REOPEN: 'ticket:reopen',
    RESOLVE: 'ticket:resolve',
    UPDATE: 'ticket:update',
  },
  USER: {
    ACTIVATE: 'user:activate',
    CREATE: 'user:create',
    DEACTIVATE: 'user:deactivate',
    DELETE: 'user:delete',
    MANAGE: 'user:manage',
    MANAGE_GROUPS: 'user:manage_groups',
    MANAGE_PERMISSIONS: 'user:manage_permissions',
    MANAGE_ROLES: 'user:manage_roles',
    READ: 'user:read',
    READ_ALL: 'user:read_all',
    RESET_PASSWORD: 'user:reset_password',
    UPDATE: 'user:update',
  },
  WORKFLOW: {
    CREATE: 'workflow:create',
    DELETE: 'workflow:delete',
    PUBLISH: 'workflow:publish',
    READ: 'workflow:read',
    READ_ALL: 'workflow:read_all',
    SIMULATE: 'workflow:simulate',
    UPDATE: 'workflow:update',
    WRITE: 'workflow:write',
  },
};