// <auto-generated />
using System;
using System.Net;
using Adrenalin.Persistence.Context;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adrenalin.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601071714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RegionCode")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("region_code");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("TierCode")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RegionCode");

                    b.HasIndex("TierCode");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("groups", "auth");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("resource");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("permissions_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("Resource", "Action")
                        .IsUnique()
                        .HasDatabaseName("uq_permissions_resource_action");

                    b.ToTable("permissions", "auth", t =>
                        {
                            t.HasComment("Atomic resource:action pairs. Examples: ticket:assign, company:create, ticket:delete. Permissions are system-defined and should not change without a migration.");
                        });
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text")
                        .HasColumnName("created_by_ip");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text")
                        .HasColumnName("revoked_by_ip");

                    b.Property<DateTime?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("idx_refresh_tokens_family");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user");

                    b.ToTable("refresh_tokens", "auth", t =>
                        {
                            t.HasComment("Stores hashed refresh tokens with family-based rotation tracking.");
                        });
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_roles_name_exact");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("roles", "auth", t =>
                        {
                            t.HasComment("Named roles: junior_agent, team_lead, manager, admin, collaborator, pmo. System roles (is_system_role=true) cannot be deleted via admin UI.");
                        });
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("role_permissions_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_role_permissions_role");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("uq_role_permissions");

                    b.ToTable("role_permissions", "auth");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.TokenBlacklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("BlacklistedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blacklisted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("jti");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("token_blacklists_pkey");

                    b.HasIndex("Jti")
                        .IsUnique()
                        .HasDatabaseName("uq_token_blacklists_jti");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_token_blacklists_user");

                    b.ToTable("token_blacklists", "auth", t =>
                        {
                            t.HasComment("Revoked JWT IDs. Auth middleware performs O(1) lookup on Jti before accepting any token.");
                        });
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .HasColumnType("text")
                        .HasColumnName("normalized_username");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lead");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_groups_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("idx_user_groups_group")
                        .HasFilter("(is_deleted = false)");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_groups_user")
                        .HasFilter("(is_deleted = false)");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_groups");

                    b.ToTable("user_groups", "auth");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.UserOtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeliveryTarget")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("delivery_target");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("purpose");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("user_otp_codes_pkey");

                    b.HasIndex("CodeHash")
                        .HasDatabaseName("idx_user_otp_codes_code_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_otp_codes_user");

                    b.ToTable("user_otp_codes", "auth", t =>
                        {
                            t.HasComment("Hashed OTP codes for email/phone verification and 2FA. FailedAttempts incremented on wrong guess; IsUsed=true on successful verification.");
                        });
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_roles_pkey");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_user_roles_role")
                        .HasFilter("(is_deleted = false)");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_roles_user")
                        .HasFilter("(is_deleted = false)");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_roles");

                    b.ToTable("user_roles", "auth");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_name");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("GeoLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("geo_location");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastActiveAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("RefreshTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("refresh_token_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_sessions_pkey");

                    b.HasIndex("RefreshTokenId")
                        .HasDatabaseName("idx_user_sessions_refresh_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_sessions_user");

                    b.ToTable("user_sessions", "auth", t =>
                        {
                            t.HasComment("One row per device/login. Enables security dashboard with all active devices.");
                        });
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.UserVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("user_verification_tokens_pkey");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("idx_user_verification_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_verification_tokens_user");

                    b.ToTable("user_verification_tokens", "auth", t =>
                        {
                            t.HasComment("Hashed URL tokens for email verification and password reset flows.");
                        });
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.CustomerTier", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<int>("PriorityBump")
                        .HasColumnType("integer")
                        .HasColumnName("priority_bump");

                    b.HasKey("Code");

                    b.ToTable("customer_tiers", "lookup", t =>
                        {
                            t.HasComment("M1-M4 customer tiers. PriorityBump is used by SLA engine.");
                        });
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.GeoRegion", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<TimeOnly>("BusinessEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("business_end");

                    b.Property<TimeOnly>("BusinessStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("business_start");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<string>("WorkingDays")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("working_days");

                    b.HasKey("Code");

                    b.ToTable("geo_regions", "lookup", t =>
                        {
                            t.HasComment("Region-specific business hours and timezone.");
                        });
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.ProductModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsMandatoryForClosure")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mandatory_for_closure");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("modules", "lookup");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.ProductVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLegacy")
                        .HasColumnType("boolean")
                        .HasColumnName("is_legacy");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("product_versions", "lookup");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.SubModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<bool>("RequiresComplianceReview")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_compliance_review");

                    b.Property<bool>("RequiresDualConfirm")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_dual_confirm");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("sub_modules", "lookup");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.Group", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "CreatedByNavigation")
                        .WithMany("GroupCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Adrenalin.unify.API.Models.Lookup.GeoRegion", "RegionCodeNavigation")
                        .WithMany("Groups")
                        .HasForeignKey("RegionCode");

                    b.HasOne("Adrenalin.unify.API.Models.Lookup.CustomerTier", "TierCodeNavigation")
                        .WithMany("Groups")
                        .HasForeignKey("TierCode");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "UpdatedByNavigation")
                        .WithMany("GroupUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("RegionCodeNavigation");

                    b.Navigation("TierCodeNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.Permission", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "CreatedByNavigation")
                        .WithMany("PermissionCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("permissions_created_by_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "UpdatedByNavigation")
                        .WithMany("PermissionUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("permissions_updated_by_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.RefreshToken", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.RefreshToken", "ReplacedByToken")
                        .WithMany("InverseReplacedByToken")
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("refresh_tokens_replaced_by_token_id_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fkey");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.Role", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "CreatedByNavigation")
                        .WithMany("RoleCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("roles_created_by_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "UpdatedByNavigation")
                        .WithMany("RoleUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("roles_updated_by_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.RolePermission", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "CreatedByNavigation")
                        .WithMany("RolePermissionCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("role_permissions_created_by_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_permission_id_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_role_id_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "UpdatedByNavigation")
                        .WithMany("RolePermissionUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("role_permissions_updated_by_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Permission");

                    b.Navigation("Role");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.TokenBlacklist", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "User")
                        .WithMany("TokenBlacklists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("token_blacklists_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.User", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "CreatedByNavigation")
                        .WithMany("InverseCreatedByNavigation")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "UpdatedByNavigation")
                        .WithMany("InverseUpdatedByNavigation")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.UserGroup", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "CreatedByNavigation")
                        .WithMany("UserGroupCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_groups_created_by_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_groups_group_id_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_groups_user_id_fkey");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.UserOtpCode", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "User")
                        .WithMany("UserOtpCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_otp_codes_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.UserRole", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "AssignedByNavigation")
                        .WithMany("UserRoleAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_roles_assigned_by_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "CreatedByNavigation")
                        .WithMany("UserRoleCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_roles_created_by_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "UpdatedByNavigation")
                        .WithMany("UserRoleUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_roles_updated_by_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_user_id_fkey");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Role");

                    b.Navigation("UpdatedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.UserSession", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.RefreshToken", "RefreshToken")
                        .WithMany("UserSessions")
                        .HasForeignKey("RefreshTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_sessions_refresh_token_id_fkey");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_sessions_user_id_fkey");

                    b.Navigation("RefreshToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.UserVerificationToken", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "User")
                        .WithMany("UserVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_verification_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.ProductModule", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "CreatedByNavigation")
                        .WithMany("ModuleCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "UpdatedByNavigation")
                        .WithMany("ModuleUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.ProductVersion", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "CreatedByNavigation")
                        .WithMany("ProductVersionCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "UpdatedByNavigation")
                        .WithMany("ProductVersionUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.SubModule", b =>
                {
                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "CreatedByNavigation")
                        .WithMany("SubModuleCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Adrenalin.unify.API.Models.Lookup.ProductModule", "ProductModule")
                        .WithMany("SubModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adrenalin.unify.API.Models.AuthModels.User", "UpdatedByNavigation")
                        .WithMany("SubModuleUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ProductModule");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.Group", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.RefreshToken", b =>
                {
                    b.Navigation("InverseReplacedByToken");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.AuthModels.User", b =>
                {
                    b.Navigation("GroupCreatedByNavigations");

                    b.Navigation("GroupUpdatedByNavigations");

                    b.Navigation("InverseCreatedByNavigation");

                    b.Navigation("InverseUpdatedByNavigation");

                    b.Navigation("ModuleCreatedByNavigations");

                    b.Navigation("ModuleUpdatedByNavigations");

                    b.Navigation("PermissionCreatedByNavigations");

                    b.Navigation("PermissionUpdatedByNavigations");

                    b.Navigation("ProductVersionCreatedByNavigations");

                    b.Navigation("ProductVersionUpdatedByNavigations");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RoleCreatedByNavigations");

                    b.Navigation("RolePermissionCreatedByNavigations");

                    b.Navigation("RolePermissionUpdatedByNavigations");

                    b.Navigation("RoleUpdatedByNavigations");

                    b.Navigation("SubModuleCreatedByNavigations");

                    b.Navigation("SubModuleUpdatedByNavigations");

                    b.Navigation("TokenBlacklists");

                    b.Navigation("UserGroupCreatedByNavigations");

                    b.Navigation("UserGroups");

                    b.Navigation("UserOtpCodes");

                    b.Navigation("UserRoleAssignedByNavigations");

                    b.Navigation("UserRoleCreatedByNavigations");

                    b.Navigation("UserRoleUpdatedByNavigations");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSessions");

                    b.Navigation("UserVerificationTokens");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.CustomerTier", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.GeoRegion", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Adrenalin.unify.API.Models.Lookup.ProductModule", b =>
                {
                    b.Navigation("SubModules");
                });
#pragma warning restore 612, 618
        }
    }
}
